"""S4: Stderr Audit -- verify hook scripts emit clean stderr.

Track C Phase 0: Run each hook script with realistic inputs and assert that
stderr contains no Python tracebacks, raw JSON dumps, or unexpected output.
This catches stderr leakage that could corrupt TUI rendering or confuse users.

Scripts tested:
  - memory_triage.py (Stop hook)
  - memory_retrieve.py (UserPromptSubmit hook)
  - memory_write_guard.py (PreToolUse:Write guard)
  - memory_staging_guard.py (PreToolUse:Bash guard)
  - memory_validate_hook.py (PostToolUse:Write validation)
"""

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).parent.parent / "hooks" / "scripts"
PYTHON = sys.executable

# Patterns that should NEVER appear in stderr during normal operation
FORBIDDEN_PATTERNS = [
    re.compile(r"Traceback \(most recent call last\)", re.IGNORECASE),
    re.compile(r"^\s*File \".*\", line \d+", re.MULTILINE),
    re.compile(r"^\w+Error:", re.MULTILINE),  # ValueError:, TypeError:, etc.
    re.compile(r"^\w+Exception:", re.MULTILINE),
    re.compile(r"^\w+Warning:", re.MULTILINE),  # UserWarning:, DeprecationWarning:, etc.
    re.compile(r"validation error for", re.IGNORECASE),  # pydantic v2 validation errors
    re.compile(r"^\{\"schema_version\"", re.MULTILINE),  # Raw memory JSON leak
    re.compile(r"^\[?\{\"type\":\s*\"", re.MULTILINE),  # Raw message JSON leak
]

# Known acceptable stderr patterns (structured logging, warnings)
ALLOWED_PATTERNS = [
    re.compile(r"^\[memory_\w+\]", re.MULTILINE),  # Prefixed log messages
    re.compile(r"^WARNING:", re.MULTILINE | re.IGNORECASE),
    re.compile(r"^DEBUG:", re.MULTILINE | re.IGNORECASE),
]


def _check_stderr(stderr_text, script_name):
    """Assert stderr is clean: no forbidden patterns unless whitelisted."""
    if not stderr_text.strip():
        return  # Empty stderr is always clean

    for pattern in FORBIDDEN_PATTERNS:
        match = pattern.search(stderr_text)
        if match:
            # Check if line is an allowed pattern
            line = stderr_text[max(0, match.start() - 80):match.end() + 80]
            is_allowed = any(ap.search(line) for ap in ALLOWED_PATTERNS)
            if not is_allowed:
                pytest.fail(
                    f"{script_name} stderr contains forbidden pattern: "
                    f"{pattern.pattern!r}\n"
                    f"Context: ...{line}..."
                )


def _user_msg(text):
    return {"type": "user", "message": {"role": "user", "content": text}}


def _assistant_msg(text):
    return {
        "type": "assistant",
        "message": {
            "role": "assistant",
            "content": [{"type": "text", "text": text}],
        },
    }


def _setup_project(tmp_path):
    """Create minimal project structure."""
    proj = tmp_path / "proj"
    claude_dir = proj / ".claude" / "memory"
    claude_dir.mkdir(parents=True)
    for folder in ["sessions", "decisions", "runbooks", "constraints", "tech-debt", "preferences"]:
        (claude_dir / folder).mkdir()
    config = {"triage": {"enabled": True}}
    (claude_dir / "memory-config.json").write_text(
        json.dumps(config), encoding="utf-8"
    )
    # Write a minimal index
    (claude_dir / "index.md").write_text(
        "# Memory Index\n\n"
        "<!-- Auto-generated by memory_index.py. Do not edit manually. -->\n\n"
        "- [Decision] Use JWT for auth -> .claude/memory/decisions/use-jwt.json "
        "#tags:auth,jwt\n",
        encoding="utf-8",
    )
    # Write a minimal memory file for retrieval to find
    decisions_dir = claude_dir / "decisions"
    (decisions_dir / "use-jwt.json").write_text(json.dumps({
        "schema_version": "1.0",
        "category": "decision",
        "id": "use-jwt",
        "title": "Use JWT for auth",
        "record_status": "active",
        "created_at": "2026-01-15T10:00:00Z",
        "updated_at": "2026-02-10T10:00:00Z",
        "tags": ["auth", "jwt"],
        "confidence": 0.9,
        "content": {
            "status": "accepted",
            "context": "Need stateless auth",
            "decision": "Use JWT",
            "rationale": ["Stateless"],
            "alternatives": [],
            "consequences": [],
        },
        "changes": [],
        "times_updated": 0,
    }), encoding="utf-8")
    return proj


def _write_transcript(tmp_path, messages):
    path = tmp_path / "transcript.jsonl"
    lines = [json.dumps(m) for m in messages]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _cleanup_staging(proj_path):
    """Clean up staging directory."""
    import hashlib
    import shutil
    cwd = os.path.realpath(str(proj_path))
    uid = os.geteuid()
    h = hashlib.sha256(f"{uid}:{cwd}".encode()).hexdigest()[:12]
    resolved_tmp = os.path.realpath("/tmp")
    staging = os.path.join(resolved_tmp, f".claude-memory-staging-{h}")
    if os.path.isdir(staging):
        shutil.rmtree(staging, ignore_errors=True)
    # Clean up flags
    memory_dir = os.path.join(str(proj_path), ".claude", "memory")
    for name in [".stop_hook_active", ".triage-handled", ".stop_hook_lock"]:
        try:
            os.unlink(os.path.join(memory_dir, name))
        except FileNotFoundError:
            pass


# ---------------------------------------------------------------------------
# memory_triage.py
# ---------------------------------------------------------------------------

class TestTriageStderr:
    """Stderr audit for memory_triage.py (Stop hook)."""

    def test_blocking_transcript_clean_stderr(self, tmp_path):
        """Triage with a high-activity transcript should have clean stderr."""
        proj = _setup_project(tmp_path)
        messages = []
        for i in range(15):
            messages.append(_user_msg(f"I decided to use approach {i}"))
            messages.append(_assistant_msg(f"Good decision because rationale {i}"))
        transcript = _write_transcript(tmp_path, messages)

        try:
            result = subprocess.run(
                [PYTHON, str(SCRIPTS_DIR / "memory_triage.py")],
                input=json.dumps({
                    "transcript_path": transcript,
                    "cwd": str(proj),
                }),
                capture_output=True,
                text=True,
                timeout=30,
            )
            assert result.returncode == 0
            _check_stderr(result.stderr, "memory_triage.py")
        finally:
            _cleanup_staging(proj)

    def test_nonblocking_transcript_clean_stderr(self, tmp_path):
        """Triage with minimal transcript (no categories triggered)."""
        proj = _setup_project(tmp_path)
        transcript = _write_transcript(tmp_path, [
            _user_msg("Hello"),
            _assistant_msg("Hi there"),
        ])

        try:
            result = subprocess.run(
                [PYTHON, str(SCRIPTS_DIR / "memory_triage.py")],
                input=json.dumps({
                    "transcript_path": transcript,
                    "cwd": str(proj),
                }),
                capture_output=True,
                text=True,
                timeout=30,
            )
            assert result.returncode == 0
            _check_stderr(result.stderr, "memory_triage.py")
        finally:
            _cleanup_staging(proj)

    def test_empty_stdin_clean_stderr(self, tmp_path):
        """Empty stdin should exit cleanly (no transcript)."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_triage.py")],
            input="",
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_triage.py")

    def test_malformed_json_stdin_clean_stderr(self, tmp_path):
        """Malformed JSON on stdin should exit cleanly."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_triage.py")],
            input="not valid json {{{",
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_triage.py")

    def test_missing_transcript_clean_stderr(self, tmp_path):
        """Missing transcript file should exit cleanly."""
        proj = _setup_project(tmp_path)
        try:
            result = subprocess.run(
                [PYTHON, str(SCRIPTS_DIR / "memory_triage.py")],
                input=json.dumps({
                    "transcript_path": "/nonexistent/transcript.jsonl",
                    "cwd": str(proj),
                }),
                capture_output=True,
                text=True,
                timeout=10,
            )
            assert result.returncode == 0
            _check_stderr(result.stderr, "memory_triage.py")
        finally:
            _cleanup_staging(proj)


# ---------------------------------------------------------------------------
# memory_retrieve.py
# ---------------------------------------------------------------------------

class TestRetrieveStderr:
    """Stderr audit for memory_retrieve.py (UserPromptSubmit hook)."""

    def test_normal_query_clean_stderr(self, tmp_path):
        """Normal retrieval query should have clean stderr."""
        proj = _setup_project(tmp_path)
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_retrieve.py")],
            input=json.dumps({
                "prompt": "What authentication approach should I use?",
                "cwd": str(proj),
            }),
            capture_output=True,
            text=True,
            timeout=15,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_retrieve.py")

    def test_empty_query_clean_stderr(self, tmp_path):
        """Empty/short query should exit cleanly."""
        proj = _setup_project(tmp_path)
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_retrieve.py")],
            input=json.dumps({
                "prompt": "hi",
                "cwd": str(proj),
            }),
            capture_output=True,
            text=True,
            timeout=15,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_retrieve.py")

    def test_no_index_clean_stderr(self, tmp_path):
        """Missing index file should not produce error stderr."""
        proj = tmp_path / "empty-proj"
        proj.mkdir()
        (proj / ".claude" / "memory").mkdir(parents=True)
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_retrieve.py")],
            input=json.dumps({
                "prompt": "test query",
                "cwd": str(proj),
            }),
            capture_output=True,
            text=True,
            timeout=15,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_retrieve.py")

    def test_empty_stdin_clean_stderr(self):
        """Empty stdin should exit cleanly."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_retrieve.py")],
            input="",
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_retrieve.py")


# ---------------------------------------------------------------------------
# memory_write_guard.py
# ---------------------------------------------------------------------------

class TestWriteGuardStderr:
    """Stderr audit for memory_write_guard.py (PreToolUse:Write)."""

    def test_deny_path_clean_stderr(self):
        """Denied write path should produce no stderr."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_write_guard.py")],
            input=json.dumps({
                "tool_input": {
                    "file_path": "/home/user/project/.claude/memory/decisions/test.json"
                }
            }),
            capture_output=True,
            text=True,
            timeout=5,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_write_guard.py")

    def test_allow_path_clean_stderr(self):
        """Allowed write path should produce no stderr."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_write_guard.py")],
            input=json.dumps({
                "tool_input": {
                    "file_path": "/tmp/some-random-file.txt"
                }
            }),
            capture_output=True,
            text=True,
            timeout=5,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_write_guard.py")

    def test_empty_stdin_clean_stderr(self):
        """Empty stdin should not crash."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_write_guard.py")],
            input="",
            capture_output=True,
            text=True,
            timeout=5,
        )
        # May exit non-zero on empty stdin (JSON decode error), but stderr should be clean
        _check_stderr(result.stderr, "memory_write_guard.py")

    def test_malformed_json_clean_stderr(self):
        """Malformed JSON should not produce traceback."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_write_guard.py")],
            input="not json",
            capture_output=True,
            text=True,
            timeout=5,
        )
        _check_stderr(result.stderr, "memory_write_guard.py")


# ---------------------------------------------------------------------------
# memory_staging_guard.py
# ---------------------------------------------------------------------------

class TestStagingGuardStderr:
    """Stderr audit for memory_staging_guard.py (PreToolUse:Bash)."""

    def test_deny_heredoc_clean_stderr(self):
        """Denied heredoc write should produce no stderr."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_staging_guard.py")],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {
                    "command": "cat <<'EOF' > .claude/memory/.staging/intent.json\n{}\nEOF"
                }
            }),
            capture_output=True,
            text=True,
            timeout=5,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_staging_guard.py")

    def test_allow_normal_bash_clean_stderr(self):
        """Normal bash command should produce no stderr."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_staging_guard.py")],
            input=json.dumps({
                "tool_name": "Bash",
                "tool_input": {
                    "command": "ls -la /tmp"
                }
            }),
            capture_output=True,
            text=True,
            timeout=5,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_staging_guard.py")

    def test_empty_stdin_clean_stderr(self):
        """Empty stdin should not crash."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_staging_guard.py")],
            input="",
            capture_output=True,
            text=True,
            timeout=5,
        )
        _check_stderr(result.stderr, "memory_staging_guard.py")


# ---------------------------------------------------------------------------
# memory_validate_hook.py
# ---------------------------------------------------------------------------

class TestValidateHookStderr:
    """Stderr audit for memory_validate_hook.py (PostToolUse:Write)."""

    def test_non_memory_path_clean_stderr(self):
        """Writing to a non-memory path should produce no stderr."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_validate_hook.py")],
            input=json.dumps({
                "tool_input": {
                    "file_path": "/tmp/random-file.txt"
                }
            }),
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_validate_hook.py")

    def test_valid_memory_file_clean_stderr(self, tmp_path):
        """Valid memory file should produce no error stderr."""
        # Create a valid memory JSON file
        proj = _setup_project(tmp_path)
        mem_file = proj / ".claude" / "memory" / "decisions" / "test-valid.json"
        mem_file.write_text(json.dumps({
            "schema_version": "1.0",
            "category": "decision",
            "id": "test-valid",
            "title": "Test valid memory",
            "record_status": "active",
            "created_at": "2026-01-15T10:00:00Z",
            "updated_at": "2026-02-10T10:00:00Z",
            "tags": ["test"],
            "confidence": 0.9,
            "content": {
                "status": "accepted",
                "context": "test",
                "decision": "test",
                "rationale": ["test"],
                "alternatives": [],
                "consequences": [],
            },
            "changes": [],
            "times_updated": 0,
        }), encoding="utf-8")

        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_validate_hook.py")],
            input=json.dumps({
                "tool_input": {
                    "file_path": str(mem_file)
                }
            }),
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_validate_hook.py")

    def test_invalid_memory_file_clean_stderr(self, tmp_path):
        """Invalid memory file should trigger quarantine without traceback.

        R1 finding: the quarantine path (pydantic validation failure) was
        not tested. Pydantic errors must not leak to stderr.
        """
        proj = _setup_project(tmp_path)
        mem_file = proj / ".claude" / "memory" / "decisions" / "test-invalid.json"
        # Write structurally invalid JSON (missing required fields)
        mem_file.write_text(json.dumps({
            "schema_version": "1.0",
            "category": "decision",
            "id": "test-invalid",
            # Missing: title, record_status, created_at, updated_at, tags, content
        }), encoding="utf-8")

        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_validate_hook.py")],
            input=json.dumps({
                "tool_input": {
                    "file_path": str(mem_file)
                }
            }),
            capture_output=True,
            text=True,
            timeout=10,
        )
        assert result.returncode == 0
        _check_stderr(result.stderr, "memory_validate_hook.py")

    def test_empty_stdin_clean_stderr(self):
        """Empty stdin should not crash."""
        result = subprocess.run(
            [PYTHON, str(SCRIPTS_DIR / "memory_validate_hook.py")],
            input="",
            capture_output=True,
            text=True,
            timeout=10,
        )
        _check_stderr(result.stderr, "memory_validate_hook.py")
